//
// Scripts for applications generated by the IceBreak Application Wizard
//

// Request an action
function doAction( frm, act ) {
	var del = true;
	if (act == "DELETE" && frm.ConfirmDelete && frm.ConfirmDelete.value == "1") {
		del = window.confirm("You are about to delete the row. Click Cancel to return without deleting the Row");
	}
	if (del) {
		frm.Action.value = act;
		frm.submit();
		return true;
	}
	return false;
}

// Request an action for a row 
function doKeyAction( frm, keynum, act ) {
	frm.Keynum.value = keynum;
	doAction( frm, act );
}

// Set readOnly property for input fields based on the classes
function setInputMode( frm, act ) {
	protectClass(frm, "TypeO");
	protectClass(frm, "TypeN");
	protectClass(frm, "Protected");
	if (act == 'UPDATE') {
		protectClass(frm, "Key");
	}
}

// Set all input fields with the specified class to readOnly
function protectClass( frm, cls) {
	for (var i=0; i<frm.elements.length; i++) {
		var clsNames = frm.elements[i].className;
		var clsArr = clsNames.split(" ");
		for (var j=0; j<clsArr.length; j++) {
			if (clsArr[j] == cls) {
				frm.elements[i].readOnly = true;
				break;
			}
		}
	}
}
// Set focus on the first possible field
function setFocus( frm ) {
	for (var i=0; i<frm.elements.length; i++) {
		if (frm.elements[i].readOnly==false) {
			try {
				frm.elements[i].focus();
				break;
			}
			catch (e) {}
		}
	}
}
